english-learning-application/Models/Word.cs
using Microsoft.AspNetCore.Server.IIS.Core;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections;
using System.ComponentModel.DataAnnotations;
using static System.Net.Mime.MediaTypeNames;

namespace english_learning_application.Models
{
    [PrimaryKey(nameof(ID))]
    public class Word
	{
        public int ID { get; set; }

        //many Word to many Tag
        public List<Tag> Tags { get; set; }

        //one Word to many DisplayWord -
        public List<DisplayWord> DisplayWords { get; set; }

        //one Word to many Sentence -
        public List<Sentence> Sentences { get; set; }

        // one Word to many TranslatedSentence -
        public List<TranslatedSentence> TranslatedSentences { get; set; }

        // one Word to many TranslatedWord -
        public List<TranslatedWord> TranslatedWords { get; set; }

        //many Word to many Test -
        public List<Test> Tests { get; set; }

        //unic key
        [Required]
        public string OriginalWord { get; set; }

        public Word()
        {
            Tags = new List<Tag>();
            DisplayWords = new List<DisplayWord>();
            Sentences = new List<Sentence>();
            TranslatedSentences = new List<TranslatedSentence>();
            TranslatedWords = new List<TranslatedWord>();
            Tests = new List<Test>();
        }
    }
}

english-learning-application/Controllers/WordController.cs
using System;
using english_learning_application.Data;
using english_learning_application.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace english_learning_application.Controllers
{
	public class WordController : Controller
	{
        private readonly ApplicationDbContext _context;

        public WordController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Words
        public async Task<IActionResult> Index()
        {
            return View(await _context.Words.ToListAsync());
        }

        // GET: Words/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var word = await _context.Words
                .Include(w => w.Tags)
                .Include(w => w.DisplayWords)
                .Include(w => w.Sentences)
                .Include(w => w.TranslatedSentences)
                .Include(w => w.TranslatedWords)
                .Include(w => w.Tests)
                .FirstOrDefaultAsync(m => m.ID == id);

            if (word == null)
            {
                return NotFound();
            }

            return View(word);
        }

        // GET: Words/Create
        public IActionResult Create()
        {

            ViewData["Tags"] = _context.Tags.ToList();

            return View();
        }

        // POST: Words/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,OriginalWord")] Word word)
        {
            if (ModelState.IsValid && IsWordUnique(word.ID, word.OriginalWord))
            {
                _context.Add(word);
                if (_context.SaveChanges() != 1)
                {
                    return BadRequest();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(word);
        }

        // GET: Words/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

           

            if (id == null)
            {
                return NotFound();
            }

            var word = await _context.Words.FindAsync(id);
            if (word == null)
            {
                return NotFound();
            }
            ViewData["Tags"] = _context.Tags.ToList();

            return View(word);
        }

        // POST: Words/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,OriginalWord,Tags")] Word word)
        {
            if (id != word.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid && IsWordUnique(word.ID, word.OriginalWord))
            {
                try
                {
                    // Load the entity with its related entities
                    var entity = _context.Words
                        .Include(e => e.Tags)
                        .Single(e => e.ID == id);

                    List<int> tags = word.Tags.ToList().Select(
                        l => l.ID
                        ).ToList();

                    // Update the related entities
                    entity.Tags.Clear(); // Remove existing related entities
                    foreach (int relatedEntity in tags)
                    {
                        var relatedEntitynew = _context.Tags.Find(relatedEntity);
                        relatedEntitynew.Words.Add(entity);
                        entity.Tags.Add(relatedEntitynew);
                    }

                    // Update the word properties
                    entity.OriginalWord = word.OriginalWord;

                    // Save the changes to the database
                    if (_context.SaveChanges() != 1)
                    {
                        return BadRequest();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WordExists(word.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["Tags"] = _context.Tags.ToList();
            return View(word);
        }

        // GET: Words/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var word = await _context.Words
                .FirstOrDefaultAsync(m => m.ID == id);
            if (word == null)
            {
                return NotFound();
            }

            return View(word);
        }

        // POST: Words/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var word = await _context.Words.FindAsync(id);
            _context.Words.Remove(word);
            if (_context.SaveChanges() != 1)
            {
                return BadRequest();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool WordExists(int id)
        {
            return _context.Words.Any(e => e.ID == id);
        }

        [HttpGet]
        public JsonResult IsOriginalWordUnique(int ID, string OriginalWord)
        {
            var isUnique = !_context.Words.Any(w => w.ID != ID && w.OriginalWord == OriginalWord);
            return Json(isUnique);
        }

        public bool IsWordUnique(int ID, string OriginalWord)
        {
            return !_context.Words.Any(w => w.ID != ID && w.OriginalWord == OriginalWord);
        }
    }
}

english-learning-application/Views/Word/Create.cshtml
@model english_learning_application.Models.Word

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, english_learning_application

<h2>Create New Word</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.OriginalWord, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OriginalWord, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OriginalWord, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select multiple class="form-control" id="Tags" name="Tags">
                @foreach (var tag in ViewBag.Tags)
                {
                    <option value="@tag.ID">@tag.Name</option>
                }
            </select>
            @Html.ValidationMessageFor(model => model.Tags, "", new { @class = "text-danger" })

        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

english-learning-application/Views/Word/Delete.cshtml
@model english_learning_application.Models.Word

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, english_learning_application


<h2>Delete Word</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Word</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OriginalWord)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OriginalWord)
        </dd>
    </dl>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}

english-learning-application/Views/Word/Details.cshtml
@model english_learning_application.Models.Word

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, english_learning_application


<h2>Word Details</h2>

<div>
    <h4>Word</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.OriginalWord)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.OriginalWord)
        </dd>
    </dl>
</div>
<div>
    <h4>Tags</h4>
    <hr />
    @if (Model.Tags.Count > 0)
    {
        <ul>
            @foreach (var tag in Model.Tags)
            {
                <li>@tag.Name</li>
            }
        </ul>
    }
    else
    {
        <p>No tags found for this word.</p>
    }
</div>
<div>
    <h4>Display Words</h4>
    <hr />
    @if (Model.DisplayWords.Count > 0)
    {
        <ul>
            @foreach (var displayWord in Model.DisplayWords)
            {
                <li>@displayWord.Display</li>
            }
        </ul>
    }
    else
    {
        <p>No display words found for this word.</p>
    }
</div>
<div>
    <h4>Sentences</h4>
    <hr />
    @if (Model.Sentences.Count > 0)
    {
        <ul>
            @foreach (var sentence in Model.Sentences)
            {
                <li>@sentence.OriginalSentence</li>
            }
        </ul>
    }
    else
    {
        <p>No sentences found for this word.</p>
    }
</div>
<div>
    <h4>Translated Sentences</h4>
    <hr />
    @if (Model.TranslatedSentences.Count > 0)
    {
        <ul>
            @foreach (var translatedSentence in Model.TranslatedSentences)
            {
                <li>@translatedSentence.Translation</li>
            }
        </ul>
    }
    else
    {
        <p>No translated sentences found for this word.</p>
    }
</div>
<div>
    <h4>Translated Words</h4>
    <hr />
    @if (Model.TranslatedWords.Count > 0)
    {
        <ul>
            @foreach (var translatedWord in Model.TranslatedWords)
            {
                <li>@translatedWord.Word.OriginalWord - @translatedWord.Language</li>
            }
        </ul>
    }
    else
    {
        <p>No translated words found for this word.</p>
    }
</div>
<div>
    <h4>Tests</h4>
    <hr />
    @if (Model.Tests.Count > 0)
    {
        <ul>
            @foreach (var test in Model.Tests)
            {
                <li>@test.Options</li>
            }
        </ul>
    }
    else
    {
        <p>No tests found for this word.</p>
    }
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    <a href="@Url.Action("Index", "Word")">Back to List</a>
</p>

english-learning-application/Views/Word/Edit.cshtml
@model english_learning_application.Models.Word

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, english_learning_application

<h2>Edit Word</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.OriginalWord, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OriginalWord, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OriginalWord, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select multiple class="form-control" id="Tags" name="Tags">
                @foreach (var tag in ViewBag.Tags)
                {
                    var isSelected = Model.Tags.Any(t => t.ID == tag.ID);
                    @if (isSelected)
                    {
                        <option value="@tag.ID" selected>@tag.Name</option>
                    }
                    else
                    {
                        <option value="@tag.ID">@tag.Name</option>
                    }



                }
            </select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

english-learning-application/Views/Word/Index.cshtml
@model IEnumerable<english_learning_application.Models.Word>

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, english_learning_application

<h2>Word List</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OriginalWord)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OriginalWord)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>